---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, tiering' 
summary: Saiba o que há de novo no NetApp Cloud Tiering. 
---
= Novidades no NetApp Cloud Tiering
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba o que há de novo no NetApp Cloud Tiering.



== 06 de outubro de 2025



=== O BlueXP tiering agora é NetApp Cloud Tiering

O BlueXP tiering foi renomeado para NetApp Cloud Tiering.



=== BlueXP agora é NetApp Console

O NetApp Console, criado com base na base aprimorada e reestruturada do BlueXP , fornece gerenciamento centralizado do armazenamento NetApp e do NetApp Data Services em ambientes locais e na nuvem em nível empresarial, fornecendo insights em tempo real, fluxos de trabalho mais rápidos e administração simplificada, de forma altamente segura e compatível.

Para obter detalhes sobre o que mudou, consulte olink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de versão do NetApp Console"] .



== 09 de agosto de 2023



=== Use um prefixo personalizado para o nome do bucket

No passado, você precisava usar o prefixo padrão "fabric-pool" ao definir o nome do bucket, por exemplo, _fabric-pool-bucket1_. Agora você pode usar um prefixo personalizado ao nomear seu bucket. Essa funcionalidade está disponível somente ao hierarquizar dados no Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["Saber mais"] .



=== Pesquisar um cluster em todos os conectores BlueXP

Se você estiver usando vários Conectores para gerenciar todos os sistemas de armazenamento em seu ambiente, alguns clusters nos quais você deseja implementar camadas podem estar em Conectores diferentes. Se não tiver certeza de qual conector está gerenciando um determinado cluster, você pode pesquisar em todos os conectores usando o Cloud Tiering. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["Saber mais"] .



== 04 de julho de 2023



=== Ajuste a largura de banda para transferir dados inativos

Quando você ativa o Cloud Tiering, o ONTAP pode usar uma quantidade ilimitada de largura de banda de rede para transferir os dados inativos dos volumes no cluster para o armazenamento de objetos.  Se você perceber que o tráfego em camadas está afetando as cargas de trabalho normais dos usuários, você pode limitar a quantidade de largura de banda que pode ser usada durante a transferência. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Saber mais"] .



=== Evento de hierarquização exibido no Centro de Notificações

O evento de hierarquização "Adicionar dados adicionais do cluster <nome> ao armazenamento de objetos para aumentar sua eficiência de armazenamento" agora aparece como uma notificação quando um cluster está hierarquizando menos de 20% de seus dados inativos, incluindo clusters que não estão hierarquizando nenhum dado.

Esta notificação é uma "Recomendação" para ajudar a tornar seus sistemas mais eficientes e economizar em custos de armazenamento.  Ele fornece um link para o https://bluexp.netapp.com/cloud-tiering-service-tco["Calculadora de custo total de propriedade e economia de Cloud Tiering"^] para ajudar você a calcular sua economia de custos.



== 03 de abril de 2023



=== A aba de licenciamento foi removida

A guia Licenciamento foi removida da interface de Hierarquia de Nuvem.  Agora, todo o licenciamento para assinaturas pré-pagas (PAYGO) pode ser acessado no Painel de controle local do Cloud Tiering.  Também há um link dessa página para a BlueXP digital wallet, para que você possa visualizar e gerenciar qualquer licença do Cloud Tiering (BYOL).



=== As guias de níveis foram renomeadas e atualizadas

A aba "Painel de Clusters" foi renomeada para "Clusters", e a aba "Visão Geral On-Prem" foi renomeada para "Painel On-Premises".  Estas páginas adicionaram algumas informações que ajudarão você a avaliar se é possível otimizar seu espaço de armazenamento com configurações de camadas adicionais.



== 05 de março de 2023



=== Gerar um relatório de níveis para volumes

Você pode baixar um relatório na página Volumes em camadas para poder revisar o status de camadas de todos os volumes nos clusters que você está gerenciando.  O BlueXP Tiering gera um arquivo .CSV que você pode revisar e enviar para outras pessoas na sua empresa, conforme necessário. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#download-a-tiering-report-for-your-volumes["Veja como baixar o relatório de níveis"] .



== 06 de dezembro de 2022



=== Alterações no ponto de extremidade de acesso à Internet de saída do conector

Devido a uma alteração no Cloud Tiering, você precisa alterar os seguintes pontos de extremidade do conector para uma operação bem-sucedida do Cloud Tiering:

[cols="50,50"]
|===
| Ponto final antigo | Novo ponto final 


| \ https://cloudmanager.cloud.netapp.com | \ https://api.bluexp.netapp.com 


| \https://*.cloudmanager.cloud.netapp.com | \https://*.api.bluexp.netapp.com 
|===
Veja a lista completa de endpoints para seu https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^] , https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^] , ou https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azul"^] ambiente de nuvem.



== 06 de novembro de 2022



=== Arraste e solte para habilitar a hierarquização para destinos adicionais

Se o destino de camadas do Azure Blob, Google Cloud Storage ou StorageGRID existir como um ambiente de trabalho no Canvas, você poderá arrastar seu ambiente de trabalho ONTAP local para o destino para iniciar o assistente de configuração de camadas.



== 19 de setembro de 2022



=== Configurar o AWS PrivateLink ao hierarquizar para o Amazon S3

Em versões anteriores, era muito demorado fornecer essa maneira segura de conectar seu cluster a um bucket S3 por meio de um endpoint VPC.  Agora você pode seguir os passos pré-requisitos para https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#configure-your-system-for-a-private-connection-using-a-vpc-endpoint-interface["configure seu sistema para uma conexão privada usando uma interface de endpoint VPC"] e então você pode selecionar o PrivateLink durante o assistente de configuração de camadas na página Rede.

https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html["Revise os requisitos e as etapas para hierarquizar dados inativos no Amazon S3"] .



=== Arraste e solte para habilitar a hierarquização no Amazon S3

Se o destino de hierarquização do Amazon S3 existir como um ambiente de trabalho no Canvas, você poderá arrastar seu ambiente de trabalho ONTAP local para o destino para iniciar o assistente de configuração de hierarquização.



=== Escolha o comportamento de camadas ao remover o armazenamento de objetos espelho

Ao remover o armazenamento de objetos espelho de uma configuração do MetroCluster , você será perguntado se deseja remover também o armazenamento de objetos primário.  Você pode optar por manter o armazenamento de objetos primário anexado ao agregado ou removê-lo.



== 03 de agosto de 2022



=== Configurar armazenamentos de objetos adicionais para outros agregados

A interface de usuário do Cloud Tiering adicionou um novo conjunto de páginas para configuração de armazenamento de objetos.  Você pode adicionar novos armazenamentos de objetos, conectar vários armazenamentos de objetos a um agregado para o FabricPool Mirroring, trocar os armazenamentos de objetos primário e espelhado, excluir conexões de armazenamento de objetos a agregados e muito mais. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-object-storage.html["Saiba mais sobre a nova funcionalidade de armazenamento de objetos."]



=== Suporte de licença para configurações do MetroCluster

As licenças do Cloud Tiering agora podem ser compartilhadas com seus clusters que estão nas configurações do MetroCluster .  Você não precisa mais usar as licenças obsoletas do FabricPool para esses cenários.  Isso facilita o uso das licenças "flutuantes" do Cloud Tiering em mais clusters. https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations["Veja como licenciar e configurar esses tipos de clusters."]
